# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10VIidMiCKAhPIu5KtHrWW4YdAy-avAcJ
"""

import tensorflow as tf

from  tensorflow.keras.datasets import fashion_mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Flatten
from tensorflow.keras.utils import to_categorical
import matplotlib.pyplot as plt

(train_images,train_labels),(test_images,test_labels)=fashion_mnist.load_data()

class_names=['T-shirt/top','Touser','pullover','Dress','coat','sandal','shirt','Sneaker','Bag','Ankle']
import numpy as np
plt.figure(figsize=(10,10))
for i in range (25):
  plt.subplot(5,5,i+1)
  plt.xticks([])
  plt.yticks([])
  plt.grid(False)
  plt.imshow(train_images[i],cmap=plt.cm.binary)
  plt.xlabel(class_names[train_labels[i]])
plt.show()

train_images=(train_images /127.5)-1
test_images=(test_images /127.5)-1

train_labels

model=Sequential([
   Flatten(input_shape=(28,28)),
   Dense(128,activation='relu'),
   Dense(10,activation='softmax')
])

model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

train_labels= to_categorical(train_labels)
test_labels= to_categorical(test_labels)

history = model.fit(
    train_images,
    train_labels,
    epochs=20,
    validation_data=(test_images, test_labels)
)

print(train_images.shape)
print(train_labels.shape)



y_pred =model.predict(test_images)
y_pred_classes =np.argmax(y_pred,axis=1)
y_true=np.argmax(test_labels,axis=1)

cm= confusion_matrix(y_true, y_pred_classes)

plt.figure(figsize=(10,10))

sns.heatmap(cm,annot=True,fmt='d',camp='Blues')
plt.title('Confusion matrix')
plt.ylabel('Actual label')
plt.xlabel('Predicted label')
plt.show()